services:
  - type: web
    name: taskmanager-api
    env: node
    buildCommand: npm install && cd server && npm install
    startCommand: node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    # Add your environment variables here:
    # - key: DATABASE_URL
    #   fromDatabase:
    #     name: taskmanager-db
    #     property: connectionString
    # - key: JWT_SECRET
    #   generateValue: true
    # - key: BCRYPT_ROUNDS
    #   value: 10

# Uncomment if you want to add a PostgreSQL database
# databases:
#   - name: taskmanager-db
#     databaseName: taskmanager
#     user: taskmanager